### ISSUE TITLE
Incompatible with Spring Boot plugin

### ISSUE THREAD

**Issue by adrianjgeorge** [nebula-plugins/nebula-dependency-recommender-plugin#10]
This plugin is incompatible with the spring boot plugin because you both try to add a dependencyManagement extension. I'd like to be able to use both. Any chance of a rename on your end?

**Comment by adrianjgeorge** [comment]
I'd consider doing it myself and submitting a potential pull request, but a clean clone of our project is unbuildable do to a NoClassDefFoundError on nebula.plugin.info.ci.POSIXUtil

**Comment by rspieldenner** [comment]
I'll open up the discussion internally.

**Comment by adrianjgeorge** [comment]
Awesome, thanks.

**Comment by adrianjgeorge** [comment]
Just so it's clear, i have no intention of using bom generation, but i get it along with the part i do want which is the recommender. Unfortunately the bom generation binds itself to dependency management, almost certainly because that's what it translates to in maven land.

**Comment by adrianjgeorge** [comment]
The contacts plugin was the reason for me being unable to build from a basic clone of the project. You might have a dependency problem there.

**Comment by adrianjgeorge** [comment]
Since I got the build working i went ahead and made the change and opened a pull request. #11
