### ISSUE TITLE
Project dependencies may introduce inconsistent version recommendations

### ISSUE THREAD

**Issue by uschi2000** [nebula-plugins/nebula-dependency-recommender-plugin#12]
Hi all,
Assume a two-project (A,B) build such that B has a project-dependency on A. A common setup is to have a top-level `versions.props` (as a recommendation source) and project level `A/versions.props` and `B/versions.props` for per-project overrides. Now, when building B, the transitive dependencies induced by the project dependency on A are erroneously resolved with the combination of the top-level `versions.props` and `B/versions.props` rather than the expected `A/versions.props`. Any suggestions for handling this scenario?
Thanks! Robert.

**Comment by rspieldenner** [comment]
would you post an example of the build.gradle so we can see how to write a
failing test, or to advise on changes to the build.gradle files?

**Comment by rpalcolea** [comment]
Closing this as lack of activity
