### ISSUE TITLE
problems with transitive dependencies

### ISSUE THREAD

**Issue by eprst** [nebula-plugins/nebula-dependency-recommender-plugin#16]
I'm probably missing something but I can't make it work with transitive dependencies. Here's a small project to illustrate the problem:

pom.xml:

    <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
      <modelVersion>4.0.0</modelVersion>
      <groupId>some</groupId>
      <artifactId>some</artifactId>
      <version>0.0-SNAPSHOT</version>
      <packaging>pom</packaging>
      <dependencyManagement>
        <dependencies>
          <dependency>
            <groupId>net.jcip</groupId>
            <artifactId>jcip-annotations</artifactId>
            <version>1.0</version>
          </dependency>
        </dependencies>
      </dependencyManagement>
    </project>

build.gradle

    plugins {
      id "nebula.dependency-recommender" version "3.5.0"
    }
    
    allprojects {
      apply plugin: "nebula.dependency-recommender"
    }
    
    dependencyRecommendations {
      mavenBom file: file('pom.xml')
    }
    
    subprojects {
      repositories {
        jcenter()
        mavenCentral()
      }
    
      apply plugin: 'java'
    }

settings.gradle

    include 'alpha', 'bravo'

alpha/build.gradle

    dependencies {
      compile project(":bravo")
    }

bravo/build.gradle

    dependencies {
      compile 'net.jcip:jcip-annotations'
    }

In other words, `alpha->bravo->net.jcip:jcip-annotations:1.0`

Seems to work inside `bravo`: 

     ❯ gradle dependencies --configuration compile
    :bravo:dependencies
    
    ------------------------------------------------------------
    Project :bravo
    ------------------------------------------------------------
    
    compile - Dependencies for source set 'main'.
    \--- net.jcip:jcip-annotations: -> 1.0

But not inside `alpha`:

     ❯ gradle dependencies --configuration compile
    :alpha:dependencies
    
    ------------------------------------------------------------
    Project :alpha
    ------------------------------------------------------------
    
    compile - Dependencies for source set 'main'.
    \--- project :bravo
         \--- net.jcip:jcip-annotations: FAILED

Here's an archive with the project:
[nebula-bug.tar.gz](https://github.com/nebula-plugins/nebula-dependency-recommender-plugin/files/328999/nebula-bug.tar.gz)

Any ideas what could be the cause?

Thanks

**Comment by DanielThomas** [comment]
Coincidentally, we happened to run into this internally for the first time today. 

Definitely a bug - in conflict resolved mode, we still need to consider first order dependencies of project dependencies candidates for recommendations. You may be able to workaround the problem by changing to the `OverrideTransitives` strategy.

**Comment by rspieldenner** [comment]
Fixed by #20 give the new version a shot

**Comment by eprst** [comment]
works, thank you!
