### ISSUE TITLE
Slight error in documentation

### ISSUE THREAD

**Issue by dbahlbeck** [nebula-plugins/nebula-dependency-recommender-plugin#22]
Hi,

On this page [Properties-File-Provider](https://github.com/nebula-plugins/nebula-dependency-recommender-plugin/wiki/Properties-File-Provider) there is a typo I think:

This code doesn't work:

```
dependencyRecommendations {
   propertiesFile file: 'recommendations.props'
}
```

It fails with `Cannot cast object 'recommendations.props' with class 'java.lang.String' to class 'java.io.File'`

It looks like a documentation error to me. Should probably be:

```
dependencyRecommendations {
   propertiesFile file: file('recommendations.props')
}
```

**Comment by rpalcolea** [comment]
This is reflected in the docs
