### ISSUE TITLE
FuzzyVersionResolver: clearly defining and improving syntax

### ISSUE THREAD

**Issue by henryptung** [nebula-plugins/nebula-dependency-recommender-plugin#27]
Currently, FuzzyVersionResolver seems to support `*` wildcards in selectors. While this makes sense, the mechanism for doing so uses a regex conversion, which fails to quote the rest of the string. As such, `com.mycompany.extensions` would match `com-mycompany-extensions` since the rest of the string is interpreted as (modified) regex.

As a secondary concern, currently nested dependency overrides are not supported (e.g. I cannot specify `com.mycompany.group:myapp-*` as one version, but set `com.mycompany.group:myapp-utils-*` to some other version, e.g. due to independent versioning. Currently, if multiple glob-style overrides apply to one version, the glob used seems to be undefined (e.g. HashMap order).

Combining these concerns, I'd propose canonicalizing syntax some more, with the following rules:

1. The only control characters are `:` and `*`; the former is the group-module separator, and the latter is a wildcard character matcher. All other characters will be matched literally.
2. Exact module match is tested first. After that, glob matchers are tested in order of decreasing specificity (where specificity = number of non-wildcard characters). 

Mostly, I'd like to enable the workflow of "obvious nested wildcard overrides", i.e.

    com.mycompany.group:myapp-* = 1.0.1
    com.mycompany.group:myapp-utils-* = 2.2.1

with the regex-escaping issue as incidental cleanup.

**Comment by ash211** [comment]
I'd be interested in using this behavior -- do the maintainers of this project feel it's in-scope for the plugin?

**Comment by henryptung** [comment]
@DanielThomas @rspieldenner Can this be safely closed now that the PR is merged?
