### ISSUE TITLE
Recommendation does not work with composite builds

### ISSUE THREAD

**Issue by vitjouda** [nebula-plugins/nebula-dependency-recommender-plugin#32]
I am not really sure if you can do something about this, but at least it can be noted for future reference or other people dealing with the same issue. Version recommendation does not work when used with composite build feature. I believe it is for the same reason as described [in this Gradle issue](https://github.com/gradle/gradle/issues/947).

**Comment by rspieldenner** [comment]
needed to fix for full composite support

**Comment by mborger** [comment]
Is there a work around for this issue? I'm curious if and how Netflix uses composite builds internally with this plugin.

**Comment by rspieldenner** [comment]
We tend to apply the same recommendation bom to all of our projects

**Comment by mborger** [comment]
I published a sample setup of what I'm trying to accomplish. Could you provide some feedback on what I'm doing wrong?
https://github.com/mborger/dependency-recommender-test

**Comment by DanielThomas** [comment]
This release is building now, try it when it's available:

https://github.com/nebula-plugins/nebula-dependency-recommender-plugin/releases/tag/v5.0.0

**Comment by mborger** [comment]
Yes that solves my issue. Thanks for the response!
