### ISSUE TITLE
Maven BOM provider uses Maven API incorrectly, producing meaningless exceptions if dependency resolution fails

### ISSUE THREAD

**Issue by zyxist** [nebula-plugins/nebula-dependency-recommender-plugin#37]
The implementation of `ModelResolver.resolveModel()` shall throw `UnresolvableModelException`, if the artifact cannot be found in any of the repositories.

The current implementation returns NULL, and the Gradle output does not contain any indication which artifact causes the problem. There is just a meaningless `IllegalArgumentException` thrown from Maven code internals.

I fixed the issue in my fork. The exception contains the full information about the artifact, and the concatenated error messages from `IOExceptions` for each of the scanned repositories, and it is printed out in the logs.

**Comment by rpalcolea** [comment]
This was fixed in https://github.com/nebula-plugins/nebula-dependency-recommender-plugin/pull/39
