### ISSUE TITLE
Maven BOM provider fails, if Maven repository requires authentication

### ISSUE THREAD

**Issue by zyxist** [nebula-plugins/nebula-dependency-recommender-plugin#38]
We have a BOM file `foo.pom` that itself has another parent POM `bar.pom` with more settings, and a Maven repository that requires authentication. Our build script was not able to find `bar.pom`, if it was not already cached in the local Maven repository.

After some investigation we noticed that Maven BOM provider ignores the `credentials` section while scanning the Maven repositories in the implementation of `ModelResolver.resolveModel()` and does not add `Authentication` HTTP header. As a result, it gets HTTP 401 Unauthorized from the server and finally, fails to resolve the dependency.

I managed to fix the issue in my fork, and the fix solved the problem for us.

**Comment by rspieldenner** [comment]
Fixed by #62
