### ISSUE TITLE
Cannot generate BOM file

### ISSUE THREAD

**Issue by viktornordling** [nebula-plugins/nebula-dependency-recommender-plugin#41]
I'm trying to generate a BOM file, but I'm getting:

```
Could not get unknown property 'dependencyManagement' for object of type 
org.gradle.api.publish.maven.internal.publication.DefaultMavenPublication.
```

Indeed if I take the sample code from [here](https://github.com/nebula-plugins/nebula-dependency-recommender-plugin#4-producing-a-maven-bom-for-use-as-a-dependency-recommendation-source) and paste it into a new project and try to run any task, I get this error.

Any hints on what I'm doing wrong? 

(I tried with a few Gradle versions, but I'm currently on 3.3.)

**Comment by ash211** [comment]
@viktornordling possibly you were following the previously-broken README example?  See the fix at https://github.com/nebula-plugins/nebula-dependency-recommender-plugin/pull/46

**Comment by viktornordling** [comment]
Yes, unless I time travelled, I was reading the broken version of the README. :) Thanks @ash211, I'll close this issue.
