### ISSUE TITLE
Honour Maven excludes in dependency-recommender

### ISSUE THREAD

**Issue by uschi2000** [nebula-plugins/nebula-dependency-recommender-plugin#48]
Producing and consuming BOMs is a great mechanism for providing library consumers with a set of known compatible dependency versions. A missing piece is for it to also honor and "recommend" dependency exclusions; Maven of course has such a mechanism (https://maven.apache.org/pom.html#Exclusions), but the Gradle Maven resolution does not currently implement it.

Would you be interested in taking a PR that implements the following feature? "When supplying version recommendations from a BOM, remove dependencies (including transitives) that were labeled as being excluded in the BOM."

**Comment by uschi2000** [comment]
FYI @markelliot

**Comment by DanielThomas** [comment]
@uschi2000 sure, however, Spring's Dependency Management plugin supports it, so if you're not tied to using our recommendations (we haven't had need for exclusions), you can try that: https://github.com/spring-gradle-plugins/dependency-management-plugin#exclusions

**Comment by rspieldenner** [comment]
Open to a PR for the feature but we won't have time to implement it ourselves for quite awhile
