### ISSUE TITLE
Documentation conflict about resolution order

### ISSUE THREAD

**Issue by jhspaybar** [nebula-plugins/nebula-dependency-recommender-plugin#5]
The README says:

"Dependency recommenders are the source of versions. If more than one recommender defines a recommended version for a module, the first recommender specified will win."

However, later in the README is a link to https://github.com/nebula-plugins/nebula-dependency-recommender-plugin/wiki/Resolving-Differences-Between-Recommendation-Providers which states:

"By default, recommendation providers are queried for recommendations in LIFO order."

I'm wondering which of these is correct?

**Comment by nadavc** [comment]
Based on https://github.com/nebula-plugins/nebula-dependency-recommender-plugin/blob/master/src/main/groovy/netflix/nebula/dependency/recommender/provider/RecommendationProviderContainer.java#L107, I believe LIFO is correct. The last recommendation provider is the one that wins.

Would you be willing to test and provide a pull request with a doc fix?

**Comment by nadavc** [comment]
Fixed in 168adf829bf03de0196475767b5bd57bea7080f6
