### ISSUE TITLE
Spring Cloud BOMs are not applied correctly

### ISSUE THREAD

**Issue by dengayevskiy** [nebula-plugins/nebula-dependency-recommender-plugin#50]
Hi! I have multi module project and there is need to import several maven BOM's, but for some reason I can't. 

Here is my **build.gradle**. In such configuration only BOM defined first will work and the version for _spring-boot-starter-websocket_ won't be resolved.
```
buildscript {
    repositories { jcenter() }

    dependencies {
        classpath 'com.netflix.nebula:nebula-dependency-recommender:4.1.0'
    }
}

allprojects {

    apply plugin: 'java'
    apply plugin: 'groovy'
    apply plugin: 'nebula.dependency-recommender'
    group = 'org.gradle.sample'
    version = '1.0'

    repositories {
        mavenCentral()
    }

    dependencyRecommendations {
        mavenBom module: 'org.springframework.cloud:spring-cloud-netflix:1.2.6.RELEASE'
        mavenBom module: 'org.springframework.boot:spring-boot-starter-parent:1.5.2.RELEASE'
    }

    configurations.all {
        it.resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
    }
}

subprojects {
    dependencies {
        compile(group: 'org.springframework.boot', name: 'spring-boot-starter-websocket')
        compile(group: 'org.springframework.cloud', name: 'spring-cloud-starter-feign')
    }
}
```

**Comment by DanielThomas** [comment]
Interesting, let me look into that @dengayevskiy. 

For Spring, you're probably better off using https://github.com/spring-gradle-plugins/dependency-management-plugin, because their plugin supports excludes and IIRC, their BOMs include them.

**Comment by DanielThomas** [comment]
Yeah, looks like this isn't as simple as multiple BOMs. Something about the Maven model building would be my guess.

This works:

```
buildscript {
    dependencies {
        classpath 'io.spring.gradle:dependency-management-plugin:1.0.0.RELEASE'
    }
}

apply plugin: 'java'
apply plugin: 'io.spring.dependency-management'

dependencyManagement {
    imports {
        mavenBom 'org.springframework.boot:spring-boot-starter-parent:1.5.2.RELEASE'
        mavenBom 'org.springframework.cloud:spring-cloud-dependencies:Camden.SR5'
    }
}

repositories {
	jcenter()
}

dependencies {
    compile 'org.springframework.boot:spring-boot-starter-websocket'
    compile 'org.springframework.cloud:spring-cloud-starter-feign'
}
```

**Comment by DanielThomas** [comment]
Added a failing test:

https://github.com/nebula-plugins/nebula-dependency-recommender-plugin/tree/issue-50

**Comment by dengayevskiy** [comment]
I think that problem is not in Spring Cloud BOM itself. This issue reproduces with every second added BOM.

**Comment by dengayevskiy** [comment]
Thanks for quick answer, guys! 

I've tried to use spring dependency management plugin but faced with another issue :( So for now i can't use any of them.
