### ISSUE TITLE
nebula dependency recommender not compatible with spring io dependency management

### ISSUE THREAD

**Issue by wilkystorm** [nebula-plugins/nebula-dependency-recommender-plugin#51]
I have a bom file which already exists and spring's io.spring.dependency-management or org.springframework.boot plugin which pulls in the former, can reference the bom file no problem in their dependencyManagement {} closure however I cannot get nebulaBomRecommender, nor nebulaDependencyManagement, nor dependencyRecommendations to work when I am also using plugin org.springframework.boot. If i remove org.springframework.boot then nebula plugins work and find the bom file but my application needs to use boot. any advice is most appreciated.

**Comment by DanielThomas** [comment]
This plugin does the same job as Spring Dependency Management. You want to to use one or the other, and we recommend theirs for Spring projects. Their plugin is also general purpose, and you can add any BOMs you need.

**Comment by wilkystorm** [comment]
Thank you very much for the clarification and guidance!
