### ISSUE TITLE
Provide errors for misconfigured version.props file

### ISSUE THREAD

**Issue by amrasarfeiniel** [nebula-plugins/nebula-dependency-recommender-plugin#56]
I spent about half an hour trying to dig into why a certain buildscript of mine wasn't properly resolving a dependency with nebula.  After getting another pair of eyes on it, it turned out I had written a:b:* = 1.0.0 instead of a:* = 1.0.0 or a:b = 1.0.0.  It seems like this would be something that nebula would be able to complain about and point you to the right error instead of silently not providing the right version number, leaving me to wonder where the bug was coming from.

**Comment by rspieldenner** [comment]
We would welcome a PR with a test case.

What kind of error message would you like here? Should we error out when a
local rule or bom contains extraneous rules? Suggestions on how to tell if
a regex is intended?

We added a strictMode where direct dependencies without a matching
recommendation will fail the build saying no recommendation found.

**Comment by rpalcolea** [comment]
Closing as lack of activity
