### ISSUE TITLE
Provide ability to exclude certain gradle configurations

### ISSUE THREAD

**Issue by jotel** [nebula-plugins/nebula-dependency-recommender-plugin#58]
Some gradle configuration especially internal ones should be allowed to be excluded from applying recommendations. One of the cases would be scala project.. let's say project defines the following

```
  apply plugin: 'scala'
  apply plugin: 'nebula.dependency-recommender'

  project.dependencyRecommendations {
    strategy OverrideTransitives
    map recommendations: ['org.scala-lang:scala-library': '2.11.7']
  }

  dependencies {
    compile 'org.scala-lang:scala-library'
  }
```

dependency recommender is used to get the version `2.11.7` of `scala-library` and the `OverrideTransitives` strategy is used

In such case plugin forces the scala-library defined in `zinc` internal configuration used to compile scala sources to version 2.11.7, wheras the zinc compiler works properly at the moment only with the version defined by the scala plugin itself i.e. `2.10.x`   Very verbose solution is to do `force` to make dependency recommender plugin to omit `scala-library` in `zinc` configuration i.e.

```
configurations.zinc.resolutionStrategy { resStr ->
  eachDependency { details ->
    def req = details.requested
    if (req.name == 'scala-library') {
      resStr.force "${req.group}:${req.name}:${req.version}"
    }
  }
}
```

but the better would be to allow just to exclude `zinc` in `dependencyRecommendations` i.e.

```
  dependencyRecommendations {
    exclude 'zinc'
    [...]
  }
```

**Comment by henryptung** [comment]
Would actually support an `include` whitelist as well, but either is fine.
