### ISSUE TITLE
Ability to omit mavenBom version if it's provided elsewhere

### ISSUE THREAD

**Issue by szunami** [nebula-plugins/nebula-dependency-recommender-plugin#64]
I want to pull in library bar's BOM, and also pull in library bar.

Today I have to do something awkward like 

    dependencyRecommendations {
        map recommendations: ['com.foo:bar-lib': '0.47.3']
        mavenBom module: 'com.foo:bar-bom:0.47.3' // the version is now described twice
    }

Would prefer to do something like

    dependencyRecommendations {
        map recommendations: ['com.foo:*': '0.47.3']
        mavenBom module: 'com.foo:bar-bom' // can omit version
    }

**Comment by EtienneMiret** [comment]
This works for me. You just need to use the map notation rather than the string notation:

```
dependencyRecommendations {
  map recommendations: ['com.foo:bar-lib': '0.47.3']
  mavenBom module: [group: 'com.foo', name: 'bar-lib']
}
```
