### ISSUE TITLE
Support trailing line comments in properties files

### ISSUE THREAD

**Issue by ash211** [nebula-plugins/nebula-dependency-recommender-plugin#66]
I expected to be able to put end-of-line comments in a properties file like this:

```
com.squareup.retrofit2:* = 2.1.0
javax.ws.rs:javax.ws.rs-api = 2.0.1
org.apache.arrow:arrow-vector = 0.2.0  # because the X Y Z
org.antlr:antlr4 = 4.7
```

But then that thinks the version of `org.apache.arrow:arrow-vector` is `0.2.0  # because the X Y Z` which obviously fails to resolve from Maven...

Instead I have to move the comment above the dependency, like this:
```
com.squareup.retrofit2:* = 2.1.0
javax.ws.rs:javax.ws.rs-api = 2.0.1
# because the X Y Z
org.apache.arrow:arrow-vector = 0.2.0
org.antlr:antlr4 = 4.7
```

which breaks sorting in the file.

Would you support a PR to enable the syntax in the first example, with the trailing end-of-line comments?  I think it can be done in a similar way to `ColonFilteringReader` in https://github.com/nebula-plugins/nebula-dependency-recommender-plugin/blob/master/src/main/groovy/netflix/nebula/dependency/recommender/provider/PropertyFileRecommendationProvider.java

**Comment by DanielThomas** [comment]
Sure, sounds completely reasonable @ash211.
