### ISSUE TITLE
java plugin required when using recommender plugin

### ISSUE THREAD

**Issue by noel-yap** [nebula-plugins/nebula-dependency-recommender-plugin#7]
$ **cat build.gradle**
apply plugin: 'nebula'
apply plugin: 'nebula.dependency-recommender'
apply plugin: 'netflix.bom-publish'

dependencyRecommendations {
  map recommendations: [ 'com.google.inject.extensions:guice-servlet': '4.0' ]
}

dependencies {
  recommendation 'com.sun.jersey.contribs:jersey-guice:1.19'
}
$ **./gradlew dependencyInsight --dependency guice-servlet --configuration recommendation**
...
:dependencyInsight
com.google.inject.extensions:guice-servlet:3.0 :broken_heart: 
--- com.sun.jersey.contribs:jersey-guice:1.19
     --- recommendation

$ **cat build.gradle**
apply plugin: 'nebula'
apply plugin: 'nebula.dependency-recommender'
apply plugin: 'netflix.bom-publish'

apply plugin: 'java' :blue_heart:

dependencyRecommendations {
  map recommendations: [ 'com.google.inject.extensions:guice-servlet': '4.0' ]
}

dependencies {
  recommendation 'com.sun.jersey.contribs:jersey-guice:1.19'
}

$ **./gradlew dependencyInsight --dependency guice-servlet --configuration recommendation**
...
:dependencyInsight
com.google.inject.extensions:guice-servlet:4.0 (selected by rule) :green_heart:

com.google.inject.extensions:guice-servlet:3.0 -> 4.0
--- com.sun.jersey.contribs:jersey-guice:1.19
     --- recommendation

**Comment by noel-yap** [comment]
The latest plugin release fixes this issue but only for non-leaf projects.

**Comment by rpalcolea** [comment]
This shouldn't be an issue anymore. // cc @chali @OdysseusLives
