### ISSUE TITLE
Dependencies aren't recommended for buildscript dependencies

### ISSUE THREAD

**Issue by dinomite** [nebula-plugins/nebula-dependency-recommender-plugin#70]
This is likely either impossible because of the order things happen, or I'm doing something wrong.  I've got buildscript dependencies that I'd like to have versions recommended for.

My parent `build.gradle` sets up the recommender (and works for normal dependencies throughout my projects):

    plugins {
        id 'nebula.dependency-recommender' version '5.0.0'
    }

    dependencyRecommendations {
        strictMode = true

        map recommendations: [
                'com.avast.gradle:docker-compose-gradle-plugin'       : '0.4.5',
        ]
    }

Some of my subproject build files use the [docker-compose-gradle-plugin](https://github.com/avast/gradle-docker-compose-plugin):

    buildscript {
        dependencies {
            classpath 'com.avast.gradle:docker-compose-gradle-plugin'
        }
    }

    apply plugin: 'docker-compose'

Unfortunately, the version for d-c-g-p isn't provided and I have to manually specify it.

**Comment by DanielThomas** [comment]
The buildscript classpath is resolved in order to apply the plugin, so plugins can't apply to the buildscript.

**Comment by dinomite** [comment]
Got it, thanks for confirming my suspicion!
