### ISSUE TITLE
Gradle generated pom files when nebula recommender is used are missing dependency versions

### ISSUE THREAD

**Issue by CesarIzzat** [nebula-plugins/nebula-dependency-recommender-plugin#9]
I have ported a number of maven projects to Gradle and use the nebula recommender to manage the versions of third party artefacts.  This process works fine however I have noticed that the pom files that are being generated are not valid and cannot be processed by either Gradle or Maven.

If my component has the following dependency in the Gradle build file
                compile 'org.mdg:mdg'
The corresponding entry in the published pom file for my component has the following entry

```
      <dependency>
             <groupId>org.mdg</groupId>
             <artifactId>mdg</artifactId>
             <scope>compile</scope>
       </dependency>
```

If I include my component as a dependency in another project then I get an error from Maven and Gradle that the pom file is not valid and that they are not able to resolve transitive dependencies.

Surely the generated pom file for my component should include the group, artifact and version ids.  Where is the version id?

**Comment by rspieldenner** [comment]
you probably need to use our publishing plugin as well. We found by default
gradle needs to have the version directly in the dependencies block to
generate the pom. You could create similar logic that our plugin adds to
insert the version into the generate pom. The publishing plugin is at
https://github.com/nebula-plugins/nebula-publishing-plugin

**Comment by adrianjgeorge** [comment]
Even when using the nebula-publishing-plugin version numbers aren't being put in the pom.
